### PR TITLE
Fix/deprecation warnings

### LINKED ISSUE #5: Deprecate `orgmode.parser.*`
[It's not going to be supported anymore](https://github.com/nvim-orgmode/orgmode/issues/217)

### PR DESCRIPTION
**Pull request by lyz-code**
Closes #5

### CODE REVIEW

**Comment by lyz-code** [comment]
@kristijanhusak can you please take a look and suggest what I'm doing wrong? With these changes the plugin doesn't work with `nightly`

**Comment by kristijanhusak** [comment]
@lyz-code you are using some internals that were changed. I'll expose some API calls for you so you can leverage that instead. I'll let you know.

**Comment by kristijanhusak** [comment]
@lyz-code I just pushed https://github.com/nvim-orgmode/orgmode/commit/b47e76f404dd908ad6c652abb6b915b2be564418 to nightly branch, that adds two new API methods:

`get_closest_headline` on file class
`refile` on the main API class

This should cover all needs for your plugin here. This is a usage example:

```lua
  local api = require('orgmode.api')

  local closest_headline = api.current():get_closest_headline()

  -- Refile to the end of the destination file
  local destination = api.load('/path/to/destination/file.org')

  -- Or refile to specific headline in the destination
  local destination = api.load('/path/to/destination/file.org').headline[3]

  return api.refile({
    source = closest_headline,
    destination = destination
  })

```

**Comment by lyz-code** [comment]
Thank you so much as always for your quick answer and fix. I'll try to implement it today <3

**Comment by lyz-code** [comment]
The code is much cleaner now @kristijanhusak thank you so much. I'll wait for the `nightly` branch to be merged in order to merge this one

**Comment by kristijanhusak** [comment]
@lyz-code  Note that nightly was merged into master so you can merge this in.

**Comment by lyz-code** [comment]
Thanks for thinking of me and notifying of the merge <3

**Pull request merged**
